Allow including local node in check_if_node_is_quorum_critical
rabbitmq/rabbitmq-server pull request #10304
Opened 2024-01-10 01:00 UTC by illotum

## Proposed Changes

This is an enhancement to check_if_node_is_quorum_critical in the context of recently added nonvoters.

Currently command implicitly ignores if the local node is non-voter. This is good to test if it can be shut down, but not good to test if the sync is complete after a new member addition. Ne flag is added `--global` to check all, including the current, nodes.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

2024-01-10 02:03 UTC, michaelklishin commented
This command was introduced specifically to verify if a node is safe to shut down.

We either need a new command or perhaps make the current one take the log installation (syncing) status into account?

Most users should roughly understand what `rabbitmq-queues check_if_node_is_quorum_critical` means but what does

``` shell
rabbitmq-queues check_if_node_is_quorum_critical --global
```

means… so the version without the flag is "local"? What exactly does that mean?

2024-01-10 02:07 UTC, michaelklishin commented
If the goal is to check if the target node may be hosting any QQ replicas that are currently not considered votes because of their ongoing log installation (initial log sync), I'd suggest
something like

``` shell
rabbitmq-queues check_if_node_has_non_voting_quorum_queue_replicas
```

I am struggling to come up with a better adjective than "non-voting" but "incomplete", "out of sync" are both even less specific and can even be misleading.

2024-01-10 03:52 UTC, illotum commented
That's absolutely fair. Back to draft for now.

2024-01-18 18:06 UTC, michaelklishin commented
@illotum thank you. Should we name this `promotable_to_voter` or something more specific like that? "Promotable" in mean different things to different people, even strictly in the context of Raft, e.g. "promotable to a leader" (any replica with an up-to-date log is).

Or something like `check_if_node_has_non_voter_replicas`?

2024-01-18 19:14 UTC, illotum commented
non_voter unfortunately has other meaning within Ra -- a permanent non_voter, which obviously should not be a cause for alarm.
How about `check_if_new(_quorum)_replicas_are_progressing`, or `_in_sync`?

2024-01-18 19:22 UTC, michaelklishin commented
@illotum if you ask me, any online replica is always progressing and can be out of sync for a fraction of a second.

`check_if_new_quorum_replicas_have_finished_initial_sync` is the best I could come up with. I don't mind long command names if they are more specific :P

2024-01-21 00:23 UTC, illotum commented
I put "new" there to indicate it is for newly added replicas. But I'm good with any name truth be told, renamed it to `check_if_new_quorum_replicas_have_finished_initial_sync` and rebased.

2024-01-21 01:06 UTC, michaelklishin commented
@illotum thank you. I'd use `check_if_new_quorum_queue_replicas_have_finished_initial_sync` because "quorum replica" is not really a term we use anywhere.

2024-01-24 15:01 UTC, kjnilsson requested changes
A few minor comments as well as general feel that we don't need 3 new public functions in rabbit_quorum_queue to achieve this.

2024-01-24 16:50 UTC, michaelklishin commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +list_with_local_promotable_for_cli() ->
This is an established pattern in CLI tools. The server does the formatting, CLI tools accept a map or a list of maps that is easy to format and that does not depend on the server version (or at least does not depend on it much).

2024-01-24 16:51 UTC, michaelklishin commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +list_with_local_promotable_for_cli() ->
More specifically, we do not want CLI tools getting a record. Not only records are fragile in Erlang, in Elixir you have to explicitly hook them up from a header. We do that in a few places already but with very stable records (like `listener`).

2024-01-24 18:03 UTC, SimonUnge commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +                                                  when State == follower;
Agree. Big fan of `andalso` `orelse` over `,` and `;`

2024-01-24 19:12 UTC, illotum commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +         filter_promotable/2,
filter_quorum_critical is. But sure, I'll embed the test that uses it.

2024-01-24 20:23 UTC, illotum commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +list_with_local_promotable_for_cli() ->
I take it as "keep as-is" then? If I weren't following existing patterns I'd probably default to Karl's approach, but there was a pattern indeed.

2024-01-25 00:41 UTC, michaelklishin commented on deps/rabbit/src/rabbit_quorum_queue.erl
> +list_with_local_promotable_for_cli() ->
Yes, let's keep this because dealing with records in CLI tools is not worth the gain

2024-01-27 04:08 UTC, merged