Add ssl_options to rabbitmq_auth_backend_http's schema
rabbitmq/rabbitmq-server pull request #11344
Opened 2024-05-29 13:20 UTC by MarcialRosales

## Proposed Changes

Address feature request #10281

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

2024-05-31 19:24 UTC, lukebakken commented on deps/rabbitmq_auth_backend_http/src/rabbit_auth_backend_http.erl
> +            Opts1 = [{ssl, rabbit_networking:fix_ssl_options(Opts0)}],
Good catch @MarcialRosales

2024-05-31 20:10 UTC, lukebakken approved these changes

2024-06-01 00:12 UTC, michaelklishin requested changes
We should not use typical certificate and key filenames for sample files with invalid data, so

`deps/rabbitmq_auth_backend_http/test/config_schema_SUITE_data/certs/cacert.pem`

with its current contents and its intended use in the test suite should instead be something like

`deps/rabbitmq_auth_backend_http/test/config_schema_SUITE_data/certs/invalid_cacert.pem`

2024-06-02 00:06 UTC, michaelklishin approved these changes

2024-06-02 00:06 UTC, michaelklishin approved these changes

2024-06-02 00:07 UTC, merged