OTP27 support
rabbitmq/rabbitmq-server pull request #11366
Opened 2024-06-04 11:07 UTC by mkuratczyk

With these changes we should be able to run the broker and pass tests on OTP27. However, the OCI image is still built using OTP26 to allow easier performance regression testing vs 3.13, since we are aware of OTP27-specific regressions. I will maintain a [separate branch](https://github.com/rabbitmq/rabbitmq-server/tree/oci-otp27) for now with an OCI built using OTP27.

since `maybe` is now a keyword, it's quoted. However, I think we should consider renaming it. We already have a bunch of `opt` and `option` types in different modules that serve the same or very similar purpose (although they use `undefined` instead of `none`). We can unify this in a separate PR.

2024-06-04 12:18 UTC, michaelklishin commented
`rabbit_types:option/1` was added as a "keyword-safe" replacement for `rabbit_types:maybe/1`, so we should simply use it across the board.

2024-06-05 13:04 UTC, lhoguin requested changes

2024-06-05 13:04 UTC, lhoguin commented on deps/rabbit/src/rabbit_fifo_dlx_worker.erl
> +-compile(nowarn_deprecated_callback).
This one should be simple enough to convert to `format_status/1`, just replace the `state` in the return value, with the map we are currently creating.

2024-06-05 13:04 UTC, lhoguin commented on deps/rabbit/src/rabbit_tracking_store.erl
> +-compile(nowarn_deprecated_callback).
The `format_status` here is empty it should be removed instead.

2024-06-05 13:04 UTC, lhoguin commented on deps/rabbit_common/src/supervisor2.erl
> +-compile(nowarn_deprecated_callback).
We can safely drop this `format_status/2` as well instead. https://github.com/erlang/otp/blob/master/lib/stdlib/src/supervisor.erl doesn't implement it either.

2024-06-06 15:23 UTC, lhoguin approved these changes
Code review is good. Didn't test it but I trust you. 🥲

2024-06-12 16:38 UTC, michaelklishin commented
The forced push was a rebase.

2024-06-18 05:32 UTC, merged

2024-06-18 11:06 UTC, mkuratczyk commented
@mergify backport v3.13.x