rabbit_khepri: Avoid throws in register_projection/0
rabbitmq/rabbitmq-server pull request #11879
Opened 2024-08-01 20:32 UTC by the-mikedavis

... TBW ...

2024-08-12 10:19 UTC, dumbbell requested changes

2024-08-12 10:19 UTC, dumbbell commented on deps/rabbit/src/rabbit_db.erl
>      end.
This starts to be a lot of Khepri-specific knowledge outside of `rabbit_khepri`. Would you mind moving this function to `rabbit_khepri`? E.g. `rabbit_khepri:init/1` like Mnesia.

While here, the log message level should be decreased to NOTICE or INFO probably. Perhaps we can add the equivalent of the "DB: initialize Mnesia" log message too.

2024-08-12 11:51 UTC, the-mikedavis commented
Yeah let's wait for that since we also want the `fence` API to await a leader (as [mentioned above](https://github.com/rabbitmq/rabbitmq-server/pull/11879#discussion_r1713455937))

2024-09-05 13:34 UTC, dumbbell commented
Khepri 0.15.0 is now released and used in RabbitMQ `main` branch.

2024-09-09 12:58 UTC, dumbbell requested changes
The patch looks good to me. I just made a minor style-related comment.

2024-09-09 12:58 UTC, dumbbell commented on deps/rabbit/src/rabbit_khepri.erl
> +                  %% return `{error, exists}` for projections which already exist.
The comments should be wrapped to fit into the 80-col limit.

2024-09-09 13:11 UTC, dumbbell approved these changes
Thank you!

2024-09-09 14:29 UTC, merged

2024-09-09 14:30 UTC, the-mikedavis commented
I'll set up the backports once we have the prerequisite PRs backported. In particular this PR needs https://github.com/rabbitmq/rabbitmq-server/pull/11672