Add client-provided connection name to logging
rabbitmq/rabbitmq-server pull request #11961
Opened 2024-08-08 21:55 UTC by lukebakken

Fixes #11958

* Start by adding `ConnectionName` to the "authenticated and granted access" message for AMQP 1.0

2024-08-08 21:56 UTC, lukebakken commented
AMQP 0.9.1 keeps `log_name` in the connection state for use when outputting log messages. @ansd is that reasonable for `#v1_connection{}` in AMQP 1.0?

2024-08-12 07:47 UTC, ansd requested changes

2024-08-12 07:47 UTC, ansd commented on deps/rabbit/src/rabbit_amqp_reader.erl
> +      [ConnectionName, Username, Vhost]),
This isn't the client provided name, is it?

2024-08-12 07:51 UTC, ansd commented
To provide a similar feature to AMQP 0.9.1, I suggest logging the `container-id` as sent by the client in the `open` frame.

> Examples of containers are brokers and client applications.

The advantage is that the `container-id` is mandatory. Hence, in AMQP 1.0, we can enforce the desired behaviour that we document on our website for AMQP 0.9.1:
> The name is optional; however, developers are strongly encouraged to provide one as it would significantly simplify certain operational tasks.

2024-08-12 08:57 UTC, ansd commented
I created https://github.com/rabbitmq/rabbitmq-server/pull/11975 which supersedes this PR.

2024-08-12 15:53 UTC, closed without merging