Cancel AMQP stream consumer when local stream member is deleted
rabbitmq/rabbitmq-server pull request #12074
Opened 2024-08-21 08:40 UTC by dcorbacho

The consumer reader process is gone and there is no way to recover it as the node does not have a member of the stream anymore, so it should be cancelled/detached.

Fixes #11915

2024-08-21 11:39 UTC, kjnilsson requested changes
The original idea with the code in the coordinator was that update_stream/3 should nto return any effects and that the detection of side effects would be done in the eva_* functions. Can this same logic not be added to `eval_listener/4`?

2024-08-21 19:16 UTC, dcorbacho commented
> The original idea with the code in the coordinator was that `update_stream/3` should not return any effects and that the detection of side effects would be done in the `eval_*` functions. Can this same logic not be added to `eval_listener/4`?

Sure, I wasn't aware of it. Just updated to generate the event in `eval_listener`

2024-08-21 20:04 UTC, michaelklishin commented
Rebased.

2024-09-02 14:07 UTC, acogoluegnes approved these changes
Tested against a 3-node cluster and PerfTest, the consumer is correctly canceled when the replica is deleted.

2024-09-02 14:07 UTC, merged