Global counters
rabbitmq/rabbitmq-server pull request #3045
Opened 2021-05-18 12:28 UTC by dcorbacho

Introduces global counters using the new [seshat](https://github.com/rabbitmq/seshat) library.
Also adds some missing metrics to the stream plugin.

Requires https://github.com/rabbitmq/osiris/pull/30 & https://github.com/rabbitmq/ra/pull/221

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

2021-05-18 13:47 UTC, kjnilsson requested changes

2021-05-18 13:47 UTC, kjnilsson commented on deps/rabbit/src/rabbit_messages_counters.erl
> +    seshat_counters:new(Group, Object, ?COUNTERS ++ Fields).
nice I like the meta data stuff for the counter fields

2021-05-18 14:53 UTC, dcorbacho commented on deps/rabbit/src/rabbit_messages_counters.erl
> +-module(rabbit_messages_counters).
@gerhard @mkuratczyk ?

2021-05-20 10:48 UTC, gerhard commented on deps/rabbit/src/rabbit_messages_counters.erl
> +-module(rabbit_messages_counters).
@kjnilsson + @gerhard:

We should start with more generic counters, and then refine them on a per-protocol basis. We still need the globals to work correctly and independently of the protocol-specific ones.

2021-06-21 16:48 UTC, gerhard commented
Superseded by https://github.com/rabbitmq/rabbitmq-server/pull/3127

2021-06-21 16:48 UTC, closed without merging