Try to start after cluster recovery
rabbitmq/rabbitmq-server pull request #3808
Opened 2021-11-29 07:05 UTC by tomyouyou

If it fails, the broker will hang here forever.

2021-11-29 15:01 UTC, lukebakken commented
Hello! Could you let us know how this was discovered?

2021-11-29 15:03 UTC, lukebakken requested changes

2021-11-29 15:03 UTC, lukebakken commented on deps/rabbit/src/rabbit_node_monitor.erl
> +            catch _:_ ->
Any caught exception here should be logged.

2021-11-30 02:38 UTC, tomyouyou commented
> Hello! Could you let us know how this was discovered?
@ lukebakken 
In July, in my cluster environment, there was a network failure and a node could not be recovered. The broker has gone to the recovery startup process, but it hung up after an exception. Later, it was recovered by manually restarting the rabbitmq service.
But the log file at that time could not be found again.

2021-11-30 11:46 UTC, closed without merging

2021-11-30 11:47 UTC, michaelklishin commented
We don't have enough information to work with and this stops the node with the exit code of `0` on any exception. This is a curious approach and doesn't seem to be necessary if the goal is to get logs (which I think you will anyway, from the crash report).

So it's not clear how to reproduce or what problem exactly we are solving => we cannot accept this.