Hide new ets listeners table behind a feature flag
rabbitmq/rabbitmq-server pull request #5314
Opened 2022-07-22 13:05 UTC by dcorbacho

`listener_records_to_ets`

Keep mnesia support
Allows to run in a mixed-version cluster

## Types of Changes
- [x] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

2022-07-22 13:16 UTC, dumbbell requested changes

2022-07-22 13:16 UTC, dumbbell commented on deps/rabbit/src/rabbit_core_ff.erl
> +            {error, Reason}
I'm currently working on improving the callbacks and their spec, but the `post_enable` callback should always return `ok`. At that point, the feature flag is enabled and only non-criticals operations (like this cleanup) can happen at this stage.

The return value is ignored anyway, but this is just to make it clear that there is no rollback for instance.

2022-07-25 07:37 UTC, pjk25 commented
@mergifyio rebase

2022-07-25 10:56 UTC, dumbbell approved these changes

2022-07-25 12:12 UTC, merged