Add StreamInfo command to stream protocol
rabbitmq/rabbitmq-server pull request #5427
Opened 2022-08-03 12:40 UTC by acogoluegnes

It returns general information on a stream, the first and committed offsets for now.

Fixes #5412

2022-08-08 14:21 UTC, kjnilsson requested changes

2022-08-08 14:21 UTC, kjnilsson commented on deps/rabbitmq_stream/src/rabbit_stream_reader.erl
> +                            case gen:call(MemberPid, '$gen_call',
I have prepared a PR for a new osiris API that can be used for this and that addresses the first offset init issue: https://github.com/rabbitmq/osiris/pull/101

2022-08-08 16:12 UTC, acogoluegnes commented on deps/rabbitmq_stream/src/rabbit_stream_reader.erl
> +                                          rabbit_data_coercion:to_binary(
I switched to `atom_to_binary/1` but `rabbit_data_coercion` in other places of the plugin, I can change the other occurrences in another PR. What's the deal with depending on `rabbit_common`?

2022-08-08 16:12 UTC, acogoluegnes commented on deps/rabbitmq_stream/docs/PROTOCOL.adoc
> +  Value => string
Using string => int64 instead.

2022-08-08 16:13 UTC, acogoluegnes commented on deps/rabbitmq_stream/src/rabbit_stream_reader.erl
> +                            case gen:call(MemberPid, '$gen_call',
Using new `osiris:get_stats/1` function.

2022-08-08 16:13 UTC, acogoluegnes commented on deps/rabbitmq_stream/src/rabbit_stream_reader.erl
> +                                    #{<<"first_offset">> =>
Fixed in https://github.com/rabbitmq/osiris/pull/101.

2022-08-09 08:36 UTC, kjnilsson approved these changes

2022-08-09 08:40 UTC, merged