Use latin1 as a fallback
rabbitmq/rabbitmq-server pull request #5551
Opened 2022-08-18 18:30 UTC by lukebakken

This is necessary since `cmd.exe` uses ISO-8859-1 encoding and directories can have latin1 characters, like `RabbitMQ Sérvér`

Follow-up to #5486

Discovered by @dumbbell

2022-08-18 23:07 UTC, michaelklishin requested changes
The `rabbitmq_peer_discovery_consul` seems legit, I can reproduce it locally with

``` shell
bazel test --config=local "//deps/rabbitmq_peer_discovery_consul:all"
```

Here are some details:

```
=== Ended at 2022-08-18 23:04:43
=== Location: [{rabbitmq_peer_discovery_consul_SUITE,registration_with_all_default_values_test,[453](file:///private/var/tmp/_bazel_antares/c3f94dc2f554fe15d75a378c45c3469d/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/deps/rabbitmq_peer_discovery_consul/rabbitmq_peer_discovery_consul_SUITE/test.outputs/outputs/ct_run.ct-rabbitmq_peer_discovery_consul-rabbitmq_peer_discovery_consul_SUITE@klishinm-a01.2022-08-18_23.04.41/deps.rabbitmq_peer_discovery_consul.rabbitmq_peer_discovery_consul_SUITE.logs/run.2022-08-18_23.04.41/rabbitmq_peer_discovery_consul_suite.src.html#453)},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,rabbitmq_peer_discovery_consul_SUITE},
                      {line,453},
                      {expression,
                          "rabbit_peer_discovery_consul : register ( )"},
                      {expected,ok},
                      {value,{error,function_clause}}]}
  in function  rabbitmq_peer_discovery_consul_SUITE:registration_with_all_default_values_test/1 (rabbitmq_peer_discovery_consul_SUITE.erl, line 453)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

2022-08-19 07:53 UTC, dumbbell commented
AFAIK, Windows enforces filename encoding to UTF-16 (LE?) on disk. Our use of `cmd.exe` is the source of the problem because I think it uses legacy encodings like ISO-8859-1(5) on my french Windows to maintain backward compatibility. Therefore I suspect it performs string conversions.

Linux and other similar Unix don't enforce anything. Distributions all default to a `*.UTF-8` locale and most applications expect to deal with UTF-8-encoded filenames. But non-UTF-8-encoded filenames are still possible (while still using the default locale) and applications will display a "square character" or question mark when they fail to decode that non-UTF-8 string at best, or stop working.

Erlang strings are supposed to be lists of Unicode codepoints. I think RabbitMQ should convert input strings to Unicode the earliest possible in key places, like when it reads the output of `rabbitmq-env-conf.bat` and expect to work with Unicode strings and UTF-8-encoded binaries everywhere internally.

Therefore to solve the problem with the JSON encoding crash, I would prefer to convert whatever we try to JSON-encode at the time we get/read that string instead. In the end, there should be nothing to convert on Linux and a few strings we get because of our use of `cmd.exe` on Windows.

2022-08-19 12:52 UTC, lukebakken commented
@michaelklishin I'll check that out, thanks.

@dumbbell I still got the encoding error with the fix for the output of `rabbitmq-env-conf.bat`. I'll see if I can figure out how that `latin1` string made it to the JSON encoder.

2022-08-19 13:10 UTC, lukebakken commented
@michaelklishin that bug is fixed. `[]` was incorrectly being passed as options to `thoas`.

2022-09-20 14:32 UTC, dumbbell approved these changes
The patch looks good to me.

I tested it on a french Windows with an "é" in my home folder. RabbitMQ started just fine and the management UI looks to work correctly.

2022-09-20 15:26 UTC, lukebakken commented
Thanks @dumbbell. I will continue reviewing our use of `list_to_binary/1` to see if there are other places that should be updated. I will also test using the data given in https://github.com/rabbitmq/rabbitmq-server/discussions/5805

cc @michaelklishin

2022-09-21 16:10 UTC, lukebakken commented
Currently testing with `RABBITMQ_BASE` set to `C:\Users\bakkenl\Евгений`

2022-09-21 17:06 UTC, lukebakken commented
Aha!

```
2022-09-21T09:58:43.174000-07:00 info: FORMATTER CRASH: {"Stopping message store for directory '~s'",[[99,58,47,85,115,101,114,115,47,98,97,107,107,101,110,108,47,1045,1074,1075,1077,1085,1080,1081,47,100,98,47,114,97,98,98,105,116,64,98,97,107,107,101,110,108,45,122,48,49,45,109,110,101,115,105,97,47,109,115,103,95,115,116,111,114,101,115,47,118,104,111,115,116,115,47,57,69,82,72,66,81,72,57,52,72,52,83,54,89,55,68,90,66,49,77,88,73,78,67,48,47,109,115,103,95,115,116,111,114,101,95,112,101,114,115,105,115,116,101,110,116]]}
```

2022-09-21 17:14 UTC, lukebakken commented
Running into cuttlefish errors as well when setting configuration paths using unicode:

[rabbitmq.conf.txt](https://github.com/rabbitmq/rabbitmq-server/files/9618964/rabbitmq.conf.txt)

2022-09-21 17:27 UTC, lukebakken commented
OK to keep the scope reasonable for this PR, I think I will deal with the format crash above, and leave the other unicode issues to the future, since I think fixes in cuttlefish will be required.

2022-09-23 00:10 UTC, lukebakken commented
@dumbbell @michaelklishin - I fixed all the format strings dealing with vhost names, since I tested with a vhost named `RabbitMQ Sérvér/Евгений` (with tags `Евгений, foo bar, Sérvér`).

My guess is that all `~s` and `~p` format strings in the codebase can be changed to `~ts` and `~tp`.

In order to see the unicode correctly in the `werl.exe` window, I had to set the following:

```
RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=+pc unicode
```

I of course set the following as a system env var to test everything out:

```
RABBITMQ_BASE=C:\ProgramData\RabbitMQ Sérvér\Евгений
```

Config files from that location: [Евгений.zip](https://github.com/rabbitmq/rabbitmq-server/files/9630095/default.zip)

I'm going to do a similar set of tests on Linux

2022-09-23 20:12 UTC, lukebakken commented
Here is how I tested on Linux:

* Create a generic unix package from this branch
* Create a directory like `/tmp/RabbitMQ Sérvér - Евгений`
* Copy the configuration files [from here](https://github.com/lukebakken/rabbitmq/tree/main/server/5551/RabbitMQ%20S%C3%A9rv%C3%A9r%20-%20%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9) into that directory. You'll have to edit `rabbitmq-env.conf` to point the base dir to whatever you created above
* Start the generic unix package this way:
    ```
    RABBITMQ_CONF_ENV_FILE="/path/to/rabbitmq-env.conf" ./sbin/rabbitmq-plugins enable rabbitmq_management rabbitmq_top
    LOG=debug RABBITMQ_ALLOW_INPUT=true RABBITMQ_CONF_ENV_FILE="/path/to/rabbitmq-env.conf" ./sbin/rabbitmq-server
    ```
* Investigate the output and log files to ensure there aren't any lists of integers or mis-encoded unicode strings

2022-09-24 15:15 UTC, michaelklishin commented
Using the following `rabbitmq-env.conf` at `/tmp/Евгений/rabbitmq-env.conf`:

```
readonly _rabbitmq_env_base_dir='/tmp/Евгений'
ADVANCED_CONFIG_FILE="$_rabbitmq_env_base_dir/advanced.config"
CONFIG_FILE="$_rabbitmq_env_base_dir/rabbitmq.conf"
ENABLED_PLUGINS_FILE="$_rabbitmq_env_base_dir/enabled_plugins"
LOG_BASE="$_rabbitmq_env_base_dir/log"
MNESIA_BASE="$_rabbitmq_env_base_dir/db"
SERVER_ADDITIONAL_ERL_ARGS='+pc unicode'
cat: bat: No such file or directory
#!/bin/sh

readonly _rabbitmq_env_base_dir='/tmp/Евгений'
ADVANCED_CONFIG_FILE="$_rabbitmq_env_base_dir/advanced.config"
CONFIG_FILE="$_rabbitmq_env_base_dir/rabbitmq.conf"
ENABLED_PLUGINS_FILE="$_rabbitmq_env_base_dir/enabled_plugins"
LOG_BASE="$_rabbitmq_env_base_dir/log"
MNESIA_BASE="$_rabbitmq_env_base_dir/db"
SERVER_ADDITIONAL_ERL_ARGS='+pc unicode'
```

I get the below exception. The exception goes away as soon as I move the env file to `/tmp/Eugene/rabbitmq-env.conf`.

```
2022-09-24 13:25:42.133427+04:00 [debug] <0.140.0> Sourcing $RABBITMQ_CONF_ENV_FILE: /tmp/Евгений/rabbitmq-env.conf
2022-09-24 13:25:42.137461+04:00 [debug] <0.140.0> $RABBITMQ_CONF_ENV_FILE exit status: 0

BOOT FAILED
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0> BOOT FAILED
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0> ===========
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0> Exception during startup:
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0> error:function_clause
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>     unicode_util:cpl/2, line 301
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>         args: [{error,"+ . $'/tmp/",
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                       <<"Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹/rabbitmq-env.conf'\n++ readonly $'_rabbitmq_env_base_dir=/tmp/Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹'\n++ _rabbitmq_env_base_dir=$'/tmp/Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹'\n">>},
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                [[{error,"++ ADVANCED_CONFIG_FILE=$'/tmp/",
2022-09-24 13:25:42.14===========
Exception during startup:
1598+04:00 [error] <0.140.0>                         <<"Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹/advanced.config'\n++ CONFIG_FILE=$'/tmp/Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹/rabbitmq.conf'\n++ ENABLED_PLUGINS_FILE=$'/tmp/Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹/enabled_plugins'\n">>}],
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                 [{error,"++ LOG_BASE=$'/tmp/",
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                         <<"Ð\\225Ð²Ð³ÐµÐ½Ð¸Ð¹/log'\n">>}],
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                 [{error,"++ MNESIA_BASE=$'/tmp/",
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                         <<208,92,50,50,53,208,178,208,179,208,181,208,189,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           208,184,208,185,47,100,98,39,10,43,43,32,83,69,82,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           86,69,82,95,65,68,68,73,84,73,79,78,65,76,95,69,82,
2022-09-
error:function_clause
24 13:25:42.141598+04:00 [error] <0.140.0>                           76,95,65,82,71,83,61,39,43,112,99,32,117,110,105,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           99,111,100,101,39,10,43,32,101,99,104,111,32,45,45,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           45,45,45,86,65,82,83,45,80,73,68,45,54,56,48,48,51,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           45,45,45,45,45,10,45,45,45,45,45,86,65,82,83,45,80,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           73,68,45,54,56,48,48,51,45,45,45,45,45,10,43,32,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           115,101,116,10,65,68,86,65,78,67,69,68,95,67,79,78,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           70,73,71,95,70,73,76,69,61,47,116,109,112,47,208,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           149,208,178,208,179,208,181,208,189,208,184,208,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           185,47,97,100,118,97,110,99,101,100,46,99,111,110,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           102,105,103,10,65,76,84,69,82,78,65,84,69,95,69,68,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           73,84,79,82,61,39,101,109,97,99,115,32,45,110,119,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           32,45,81,39,10,66,65,83,72,61,47,98,105,110,47,115,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           104,10,66,65,83,72,95,65,82,71,67,61,40,41,10,66,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           65,83,72,95,65,82,71,86,61,40,41,10,66,65,83,72,95,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           69,88,69,67,85,84,73,79,78,95,83,84,82,73,78,71,61,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           39,46,32,34,47,116,109,112,47,208,149,208,178,208,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           179,208,181,208,189,208,184,208,185,47,114,97,98,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           98,105,116,109,113,45,101,110,118,46,99,111,110,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           102,34,32,38,38,32,101,99,104,111,32,34,45,45,45,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           45,45,86,65,82,83,45,80,73,68,45,54,56,48,48,51,45,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           45,45,45,45,34,32,38,38,32,115,101,116,39,10,66,65,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           83,72,95,76,73,78,69,78,79,61,40,41,10,66,65,83,72,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           95,83,79,85,82,67,69,61,40,41,10,66,65,83,72,95,86,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           69,82,83,73,78,70,79,61,40,91,48,93,61,34,51,34,32,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           91,49,93,61,34,50,34,32,91,50,93,61,34,53,55,34,32,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           91,51,93,61,34,49,34,32,91,52,93,61,34,114,101,108,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           101,97,115,101,34,32,91,53,93,61,34,97,114,109,54,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           52,45,97,112,112,108,101,45,100,97,114,119,105,110,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           50,49,34,41,10,66,65,83,72,95,86,69,82,83,73,79,78,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           61,39,51,46,50,46,53,55,40,49,41,45,114,101,108,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>                           101,97,115,101,39,10,66,65,84,95,84,72,69,77,69,61,
2022-09-24 13:25:42.141598+04:00 [error] <0.140.0>
    unicode_util:cpl/2, line 301
        args: [{error,"+ . $'/tmp/",
                      <<"�\\225вгений/rabbitmq-env.conf'\n++ readonly $'_rabbitmq_env_base_dir=/tmp/�\\225вгений'\n++ _rabbitmq_env_base_dir=$'/tmp/�\\225вгений'\n">>},
               [[{error,"++ ADVANCED_CONFIG_FILE=$'/tmp/",
                        <<"�\\225вгений/advanced.config'\n++ CONFIG_FILE=$'/tmp/�\\225вгений/rabbitmq.conf'\n++ ENABLED_PLUGINS_FILE=$'/tmp/�\\225вгений/enabled_plugins'\n">>}],
                [{error,"++ LOG_BASE=$'/tmp/",
                        <<"�\\225вгений/log'\n">>}],
                [{error,"++ MNESIA_BASE=$'/tmp/",
                        <<208,92,50,50,53,208,178,208,179,208,181,208,189,
                          208,184,208,185,47,100,98,39,10,43,43,32,83,69,82,
                          86,69,82,95,65,68,68,73,84,73,79,78,65,76,95,69,82,
    [...]

2022-09-24 17:00 UTC, michaelklishin commented
I run into the following exception when following the QA instructions. First, here is my `/tmp/Евгений/rabbitmq-env.conf` which I simplified since the exception seems to happen when the node attempts to load and parse it:

```
ADVANCED_CONFIG_FILE="/tmp/Евгений/advanced.config"
CONFIG_FILE="/tmp/Евгений/rabbitmq.conf"
ENABLED_PLUGINS_FILE="/tmp/Евгений/enabled_plugins"
LOG_BASE="/tmp/Евгений/log"
MNESIA_BASE="/tmp/Евгений/db"
SERVER_ADDITIONAL_ERL_ARGS='+pc unicode'
```

```
LOG=debug RABBITMQ_ALLOW_INPUT=true RABBITMQ_CONF_ENV_FILE=/tmp/Евгений/rabbitmq-env.conf ./sbin/rabbitmq-server
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Eshell V13.1  (abort with ^G)
1> 2022-09-24 20:57:34.619523+04:00 [debug] <0.140.0>
2022-09-24 20:57:34.622290+04:00 [debug] <0.140.0> == Prelaunch phase [1/2] (initial pass) ==
2022-09-24 20:57:34.622307+04:00 [debug] <0.140.0>
2022-09-24 20:57:34.622321+04:00 [debug] <0.140.0> Process environment:
2022-09-24 20:57:34.622417+04:00 [debug] <0.140.0>   - ALTERNATE_EDITOR = emacs -nw -Q
2022-09-24 20:57:34.622423+04:00 [debug] <0.140.0>   - BAT_THEME = Monokai Extended
2022-09-24 20:57:34.622439+04:00 [debug] <0.140.0>   - BINDIR = /Users/antares/Tools/otp/25.1/erts-13.1/bin
2022-09-24 20:57:34.622465+04:00 [debug] <0.140.0>   - BUNNY_CERTIFICATE_DIR = /Users/antares/Development/Opensource/tls-gen.git/basic/result
2022-09-24 20:57:34.622478+04:00 [debug] <0.140.0>   - BUNNY_RABBITMQCTL = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmqctl
2022-09-24 20:57:34.622508+04:00 [debug] <0.140.0>   - BUNNY_RABBITMQ_HOSTNAME = sunnyside
2022-09-24 20:57:34.622519+04:00 [debug] <0.140.0>   - BUNNY_RABBITMQ_PLUGINS = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmq-plugins
2022-09-24 20:57:34.622527+04:00 [debug] <0.140.0>   - COLORFGBG = 15;0
2022-09-24 20:57:34.622533+04:00 [debug] <0.140.0>   - COLORTERM = truecolor
2022-09-24 20:57:34.622537+04:00 [debug] <0.140.0>   - COMMAND_MODE = unix2003
2022-09-24 20:57:34.622542+04:00 [debug] <0.140.0>   - DEFAULT_OTP_VERSION = 25.0
2022-09-24 20:57:34.622547+04:00 [debug] <0.140.0>   - EDITOR = code
2022-09-24 20:57:34.622551+04:00 [debug] <0.140.0>   - ELIXIR_VERSION = 1.13.4
2022-09-24 20:57:34.622557+04:00 [debug] <0.140.0>   - EMAIL = Michael S. Klishin <michael@novemberain.com>
2022-09-24 20:57:34.622606+04:00 [debug] <0.140.0>   - EMU = beam
2022-09-24 20:57:34.622611+04:00 [debug] <0.140.0>   - ERL_AFLAGS = -kernel shell_history enabled
2022-09-24 20:57:34.622618+04:00 [debug] <0.140.0>   - ERL_LIBS = /Users/antares/Development/RabbitMQ/alphatools/nodes/rabbitmq_server-3.11.0.5551/plugins
2022-09-24 20:57:34.622626+04:00 [debug] <0.140.0>   - ERL_MAX_ETS_TABLES = 50000
2022-09-24 20:57:34.622631+04:00 [debug] <0.140.0>   - ERL_MAX_PORTS = 65536
2022-09-24 20:57:34.622636+04:00 [debug] <0.140.0>   - ES_CLUSTER_NAME = elasticsearch
2022-09-24 20:57:34.622641+04:00 [debug] <0.140.0>   - ES_JAVA_OPTS = -Xms128m -Xmx512m
2022-09-24 20:57:34.622648+04:00 [debug] <0.140.0>   - GEM_HOME = /Users/antares/.rvm/gems/ruby-3.1.2
2022-09-24 20:57:34.622654+04:00 [debug] <0.140.0>   - GEM_PATH = /Users/antares/.rvm/gems/ruby-3.1.2:/Users/antares/.rvm/gems/ruby-3.1.2@global
2022-09-24 20:57:34.622661+04:00 [debug] <0.140.0>   - GIT_EDITOR = code --wait
2022-09-24 20:57:34.622668+04:00 [debug] <0.140.0>   - GO111MODULE = on
2022-09-24 20:57:34.622673+04:00 [debug] <0.140.0>   - HGEDITOR = code --wait
2022-09-24 20:57:34.622677+04:00 [debug] <0.140.0>   - HISTFILE = /Users/antares/.zsh_history
2022-09-24 20:57:34.622683+04:00 [debug] <0.140.0>   - HOME = /Users/antares
2022-09-24 20:57:34.622691+04:00 [debug] <0.140.0>   - HOMEBREW_NO_ENV_HINTS = 1
2022-09-24 20:57:34.622698+04:00 [debug] <0.140.0>   - HOP_RABBITMQCTL = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmqctl
2022-09-24 20:57:34.622705+04:00 [debug] <0.140.0>   - HOP_RABBITMQ_PLUGINS = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmq-plugins
2022-09-24 20:57:34.622719+04:00 [debug] <0.140.0>   - IRBRC = /Users/antares/.rvm/rubies/ruby-3.1.2/.irbrc
2022-09-24 20:57:34.622730+04:00 [debug] <0.140.0>   - ITERM_PROFILE = Default
2022-09-24 20:57:34.622735+04:00 [debug] <0.140.0>   - ITERM_SESSION_ID = w0t3p0:7405B069-E4D1-44D2-8C09-372B76A9F7AB
2022-09-24 20:57:34.622744+04:00 [debug] <0.140.0>   - JAVA_HOME = /Library/Java/JavaVirtualMachines/graalvm/Contents/Home/
2022-09-24 20:57:34.622750+04:00 [debug] <0.140.0>   - JRUBY_OPTS = --server
2022-09-24 20:57:34.622756+04:00 [debug] <0.140.0>   - KERL_BUILD_BACKEND = git
2022-09-24 20:57:34.622761+04:00 [debug] <0.140.0>   - LANG = en_US.UTF-8
2022-09-24 20:57:34.622765+04:00 [debug] <0.140.0>   - LANGOHR_RABBITMQCTL = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmqctl
2022-09-24 20:57:34.622772+04:00 [debug] <0.140.0>   - LANGOHR_RABBITMQ_PLUGINS = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmq-plugins
2022-09-24 20:57:34.622779+04:00 [debug] <0.140.0>   - LANGUAGE = en_US
2022-09-24 20:57:34.622787+04:00 [debug] <0.140.0>   - LC_ADDRESS = en_US.UTF-8
2022-09-24 20:57:34.622791+04:00 [debug] <0.140.0>   - LC_ALL = en_US.UTF-8
2022-09-24 20:57:34.622796+04:00 [debug] <0.140.0>   - LC_COLLATE = en_US.UTF-8
2022-09-24 20:57:34.622800+04:00 [debug] <0.140.0>   - LC_CTYPE = en_US.UTF-8
2022-09-24 20:57:34.622805+04:00 [debug] <0.140.0>   - LC_IDENTIFICATION = en_US.UTF-8
2022-09-24 20:57:34.622815+04:00 [debug] <0.140.0>   - LC_MEASUREMENT = en_US.UTF-8
2022-09-24 20:57:34.622820+04:00 [debug] <0.140.0>   - LC_MESSAGES = en_US.UTF-8
2022-09-24 20:57:34.622825+04:00 [debug] <0.140.0>   - LC_MONETARY = en_US.UTF-8
2022-09-24 20:57:34.622834+04:00 [debug] <0.140.0>   - LC_NAME = en_US.UTF-8
2022-09-24 20:57:34.622839+04:00 [debug] <0.140.0>   - LC_NUMERIC = en_US.UTF-8
2022-09-24 20:57:34.622844+04:00 [debug] <0.140.0>   - LC_PAPER = en_US.UTF-8
2022-09-24 20:57:34.622848+04:00 [debug] <0.140.0>   - LC_TELEPHONE = en_US.UTF-8
2022-09-24 20:57:34.622854+04:00 [debug] <0.140.0>   - LC_TERMINAL = iTerm2
2022-09-24 20:57:34.622859+04:00 [debug] <0.140.0>   - LC_TERMINAL_VERSION = 3.4.16
2022-09-24 20:57:34.622872+04:00 [debug] <0.140.0>   - LC_TIME = en_US.UTF-8
2022-09-24 20:57:34.622882+04:00 [debug] <0.140.0>   - LESS = -R
2022-09-24 20:57:34.622887+04:00 [debug] <0.140.0>   - LOG = debug
2022-09-24 20:57:34.622891+04:00 [debug] <0.140.0>   - LOGNAME = antares
2022-09-24 20:57:34.622897+04:00 [debug] <0.140.0>   - LSCOLORS = Gxfxcxdxbxegedabagacad
2022-09-24 20:57:34.622905+04:00 [debug] <0.140.0>   - MANPATH = /Users/antares/Tools/otp/25.1/lib/erlang/man:/Users/antares/Tools/otp/25.1/man:
2022-09-24 20:57:34.622913+04:00 [debug] <0.140.0>   - MARCH_HARE_RABBITMQCTL = /Users/antares/Tools/rabbitmq/generic/sbin/rabbitmqctl
2022-09-24 20:57:34.622920+04:00 [debug] <0.140.0>   - MCFLY_HISTORY = /var/folders/36/3knwd0k150z7nwzwx1c_lft80000gn/T/mcfly.XXXXXXXX.EHT5YXuf
2022-09-24 20:57:34.622932+04:00 [debug] <0.140.0>   - MCFLY_HISTORY_FORMAT = zsh-extended
2022-09-24 20:57:34.622937+04:00 [debug] <0.140.0>   - MCFLY_SESSION_ID = yd2VPEG9iVSlCOGycCTlKH5p
2022-09-24 20:57:34.622943+04:00 [debug] <0.140.0>   - MIX_ARCHIVES = /Users/antares/.kiex/mix/archives/elixir-1.13.4
2022-09-24 20:57:34.622949+04:00 [debug] <0.140.0>   - MY_RUBY_HOME = /Users/antares/.rvm/rubies/ruby-3.1.2
2022-09-24 20:57:34.622956+04:00 [debug] <0.140.0>   - NGINX_BIN_FILE = /Users/antares/Tools/nginx/current/sbin/nginx
2022-09-24 20:57:34.622962+04:00 [debug] <0.140.0>   - NGINX_PID_FILE = /Users/antares/Tools/nginx/current/logs/nginx.pid
2022-09-24 20:57:34.622970+04:00 [debug] <0.140.0>   - NODE_PATH = /usr/local/lib/node_modules/:/usr/local/share/npm/lib/node_modules/:/usr/local/lib/node
2022-09-24 20:57:34.622978+04:00 [debug] <0.140.0>   - PAGER = bat
2022-09-24 20:57:34.622983+04:00 [debug] <0.140.0>   - PATH = /Users/antares/Tools/otp/25.1/erts-13.1/bin:/Users/antares/Tools/otp/25.1/lib/erl_interface-5.3/bin:/Users/antares/Tools/otp/25.1/bin:/Users/antares/T [...]

2022-09-24 18:02 UTC, lukebakken commented
Thanks @michaelklishin I'll check into that!

2022-09-24 19:29 UTC, lukebakken commented
@michaelklishin I'm not exactly sure how, but commit https://github.com/rabbitmq/rabbitmq-server/pull/5551/commits/3c1c7ada5898b8512642af2faf203a0da6e6b976 appears to have fixed the issue. I made those changes to get some additional output as to what the problem was in `unicode:characters_to_list/1` but the issue seems to be resolved 🤔 

Let me know if it works in your env, thanks!

```
2022-09-24 12:25:36.792985-07:00 [debug] <0.140.0> Sourcing $RABBITMQ_CONF_ENV_FILE: /tmp/Евгений/rabbitmq-env.conf                                                                           2022-09-24 12:25:36.796221-07:00 [debug] <0.140.0> $RABBITMQ_CONF_ENV_FILE exit status: 0                                                                                                     2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0> $RABBITMQ_CONF_ENV_FILE output:                                                                                                            2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + . /tmp/Евгений/rabbitmq-env.conf                                                                                                       2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + ADVANCED_CONFIG_FILE=/tmp/Евгений/advanced.config                                                                                      2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + CONFIG_FILE=/tmp/Евгений/rabbitmq.conf                                                                                                 2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + ENABLED_PLUGINS_FILE=/tmp/Евгений/enabled_plugins                                                                                      2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + LOG_BASE=/tmp/Евгений/log                                                                                                              2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + MNESIA_BASE=/tmp/Евгений/db                                                                                                            2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + SERVER_ADDITIONAL_ERL_ARGS=+pc unicode                                                                                                 2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + echo -----VARS-PID-2296543-----                                                                                                        2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   -----VARS-PID-2296543-----                                                                                                               2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   + set                                                                                                                                    2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   ADVANCED_CONFIG_FILE='/tmp/Евгений/advanced.config'                                                                                      2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   ASDF_DIR='/home/lbakken/.asdf'                                                                                                           2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   BINDIR='/home/lbakken/.asdf/installs/erlang/25.1/erts-13.1/bin'                                                                          2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   CLOUDSDK_PYTHON='/usr/bin/python'                                                                                                        2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   CLOUDSDK_PYTHON_ARGS='-S'                                                                                                                2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   CLOUDSDK_ROOT_DIR='/opt/google-cloud-sdk'                                                                                                2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   CONFIG_FILE='/tmp/Евгений/rabbitmq.conf'                                                                                                 2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   CONF_ENV_FILE_PHASE='rabbtimq-prelaunch'                                                                                                 2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus'                                                                                  2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   DOCKER_BUILDKIT='1'                                                                                                                      2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   DOTNET_BUNDLE_EXTRACT_BASE_DIR='/home/lbakken/.cache/dotnet_bundle_extract'                                                              2022-09-24 12:25:36.796635-07:00 [debug] <0.140.0>   DOTNET_ROOT='/usr/share/dotnet' 
```

2022-09-25 23:32 UTC, michaelklishin commented
Yup, it works as expected now 👍

2022-09-26 14:01 UTC, michaelklishin approved these changes

2022-09-26 14:02 UTC, merged

2022-12-02 10:15 UTC, michaelklishin commented
Finally backported for `3.11.5`.