Handle error during shovel topology setup gracefully
rabbitmq/rabbitmq-server pull request #5788
Opened 2022-09-14 15:02 UTC by gomoripeti

## Proposed Changes

Eg. when the source exchange does not exist the source channel is closed during `queue.bind`, this used to cause the shovel to crash.
With this change the shovel is restarted gracefully, the same way as when eg the source queue is deleted during operation.

This is just a cosmetic change to avoid one crash log which might look scary at first.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [x] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

2022-09-18 20:38 UTC, michaelklishin commented
I can reproduce the timeouts locally with

``` sh
bazel run test-logs --config=local //deps/rabbitmq_shovel:dynamic_SUITE
```

2022-09-19 08:54 UTC, gomoripeti commented
indeed there is a bug when an autodelete condition is immediately satisfied, the parameters are not cleaned up. did not think this small change can have such side effect, good test coverage!

I used to ignore the github actions failures because I had the false impression they always failed, but I will make sure to always check them going forward. sorry about that

2022-09-19 08:55 UTC, michaelklishin commented
When Actions fail, the rest of the pipeline (that produces packages, tests them, tests the result against several client libraries) cannot start.

2022-09-19 22:22 UTC, michaelklishin requested changes
There are legitimate test failures.

2022-09-27 23:38 UTC, gomoripeti commented
closing this as it results in `delete-after=never` (aka permanent) dynamic shovels and autodelete (aka transient) shovels behaving differently in case of an error at topology setup. The autodelete shovels would not be restarted while other shovels would be, even though a topology error has nothing to do with the autodelete property.
(Initially I only considered and tested with permanent shovels)
Will reopen if I have a clearer idea on what should be the behaviour in all error cases.

2022-09-27 23:38 UTC, closed without merging