See Issue 6020. Take plugin dependency into account
rabbitmq/rabbitmq-server pull request #6289
Opened 2022-10-31 22:41 UTC by SimonUnge

## Proposed Changes

Please describe the big picture of your changes here to communicate to the RabbitMQ team why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

A pull request that doesn't explain **why** the change was made has a much lower chance of being accepted.

If English isn't your first language, don't worry about it and try to communicate the problem you are trying to solve to the best of your abilities.
As long as we can understand the intent, it's all good.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes issue #6020)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

Comments to this issue suggested querying the node of its active plugins, which would require an RPC call. I took an approach where I include a plugins dependencies instead, and thus avoiding the need to do an RPC call.

2022-11-01 09:57 UTC, michaelklishin requested changes
There is a [failure](https://app.buildbuddy.io/invocation/4eccf099-313a-4d4b-bedb-fb78a181dfde?target=%2F%2Fdeps%2Frabbitmq_cli%3Arabbitmqctl_tests) in `//deps/rabbitmq_cli:rabbitmqctl_tests`:

```
  1) test enable command will also load its dependent plugins (EnablePluginsCommandTest)
     test/plugins/enable_plugins_command_test.exs:322
     Assertion with == failed
     code:  assert RabbitMQ.CLI.Core.CommandModules.load_commands(:all, %{})["add_super_stream"] ==
              RabbitMQ.CLI.Ctl.Commands.AddSuperStreamCommand
     left:  nil
     right: RabbitMQ.CLI.Ctl.Commands.AddSuperStreamCommand
     stacktrace:
       test/plugins/enable_plugins_command_test.exs:330: (test)
--max-failures reached, aborting test suite
Finished in 160.8 seconds (7.1s async, 153.7s sync)
226 tests, 1 failure
```

2022-11-01 13:47 UTC, michaelklishin commented
To run that specific CLI suite you can use

``` sh
bazel test //deps/rabbitmq_cli:rabbitmqctl_tests --test_env TEST_FILE=test/plugins/enable_plugins_command_test.exs
```

2022-11-01 16:01 UTC, SimonUnge commented
Hm, and that was the test-case I created. I ran the test suite with 'TEST_FILE=... make test', and made sure it worked, but I guess bazel will setup a different environment! Lesson learned, I'm looking into it.

2022-11-01 18:20 UTC, SimonUnge commented
Added rabbitmq_stream_management to the list of plugins for the test suite which seemed to have been the issue.

2022-11-02 06:46 UTC, michaelklishin commented
This introduces test interference with another suite that asserts on plugin enabled:

```
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :not_enabled,
                  name: :rabbitmq_management,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :not_enabled,
                  name: :rabbitmq_management_agent,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :enabled,
                  name: :rabbitmq_stomp,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :not_enabled,
                  name: :rabbitmq_stream,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :not_enabled,
                  name: :rabbitmq_stream_management,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                },
                %{
                  enabled: :not_enabled,
                  name: :rabbitmq_web_dispatch,
                  running: false,
                  running_version: nil,
                  version: '3.12.0'
                }
              ],
              status: :node_down
            }
     stacktrace:
       test/plugins/list_plugins_command_test.exs:111: (test)
```

2022-11-02 07:42 UTC, michaelklishin commented
I will look into making these test suites more robust, they inherently rely on shared state :( and need attention from time to time.

2022-11-02 09:20 UTC, michaelklishin commented
Note that prior to version due to an issue in our Bazel Elixir toolchain, it was not possible to run CLI tests twice in a row without `bazel clean`, at least not if the first invocation had failed.

This has been addressed so working on CLI tools using Bazel is again possible.

2022-11-02 14:10 UTC, michaelklishin commented
The plugins-related CLI tests are more robust now. The failures in https://github.com/rabbitmq/rabbitmq-server/pull/6316 *might* be related, we have to investigate.

2022-11-03 07:05 UTC, michaelklishin commented
I can reproduce the CI failure in #6316 (that supersedes this PR) locally with both Bazel and Make:

``` shell
bazel test deps/rabbit/feature_flags_with_unpriveleged_user_SUITE
```

Investigating.

2022-11-03 11:03 UTC, michaelklishin commented on deps/rabbitmq_cli/lib/rabbitmq/cli/core/command_modules.ex
> +    all_plugins = PluginsHelpers.list(opts)
This change means we either have to always have the plugins directory set, including in all kinds of test environments, or avoid returning an error when the directory does not exist.

2022-11-03 13:20 UTC, michaelklishin commented
Superseded by #6316 with some extra changes to make a few (unrelated) test suites pass under Bazel.

2022-11-03 13:20 UTC, closed without merging