Check if stream coordinator is quorum critial
rabbitmq/rabbitmq-server pull request #6738
Opened 2022-12-21 14:42 UTC by mkuratczyk

Since https://github.com/rabbitmq/rabbitmq-server/commit/d8ff9918, streams are considered when checking for a potential quorum loss. Now we also consider `rabbit_stream_coordinator`.

Fixes #4890

2022-12-21 16:18 UTC, kjnilsson requested changes
A couple of questions / suggestions

2022-12-21 16:18 UTC, kjnilsson commented on deps/rabbit/src/rabbit_stream_coordinator.erl
> +    case ra:members(rabbit_stream_coordinator) of
Does this mean that if the local stream coordinator member isn't running we say it is ok to go ahead?

2022-12-21 16:18 UTC, kjnilsson commented on deps/rabbit/src/rabbit_upgrade_preparation.erl
> +        []  -> not lists:member(true, [C:is_quorum_critical() || C <- CriticalComponents]);
I like this API? should it have its own module with a behaviour definition?

2022-12-21 20:49 UTC, michaelklishin commented
@mergifyio rebase

2022-12-22 17:21 UTC, merged

2022-12-23 06:09 UTC, michaelklishin commented
@mergifyio backport v3.11.x