Add setting to disable op policy edit via API
rabbitmq/rabbitmq-server pull request #7165
Opened 2023-02-03 01:12 UTC by illotum

## Proposed Changes

This change adds a `rabbitmq_management` setting to disable operator policy edits, per #7131.

```
management.disable_operator_policy_edit = on
```

Additionally, when the setting is enabled, it hides relevant web console elements and returns a proper error in rabbitmqadmin. I wasn't sure how to proceed with the testing for these two targets, so these changes are not covered.

And I'm open to suggestions about the setting name of course.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

2023-02-03 02:47 UTC, michaelklishin requested changes
Please use [an enum of (`true`, `false`)](https://github.com/rabbitmq/rabbitmq-server/blob/ae8a1bd1ab3a7ac4ca89a505d58bebebd2aca77b/deps/rabbitmq_management/priv/schema/rabbitmq_management.schema#L36-L37) for such boolean types.

2023-02-03 06:14 UTC, illotum commented
Ah, I considered `{flag, true, false}`. That would work identical if I understand it right, is `enum` preferred for a particular reason?

2023-02-03 15:17 UTC, michaelklishin commented
We do not use `flag` anywhere and I had no idea Cuttlefish supports it.

2023-02-03 15:33 UTC, michaelklishin commented on deps/rabbitmq_management/src/rabbit_mgmt_wm_operator_policy.erl
> +    case rabbit_mgmt_util:is_edit_op_policy_disabled() of
I think such restrictions should live in a separate module, r.g. `rabbit_mgmt_features`.

2023-02-03 15:55 UTC, michaelklishin commented on deps/rabbitmq_management/priv/schema/rabbitmq_management.schema
> +{mapping, "management.disable_operator_policy_edit", "rabbitmq_management.disable_operator_policy_edit", [
I'd use `management.restrictions.operator_policy_changes.disabled` and `rabbitmq_management.restrictions.operator_policy_changes.disabled`. It'd be a bit more annoying to access this nested proplist but you'd have to do it only once in one predicate function.

2023-02-06 22:36 UTC, illotum commented
Addressed feedback & rebased, ready for review.

2023-02-06 22:36 UTC, illotum commented
Addressed feedback & rebased, ready for review.

2023-02-07 02:32 UTC, michaelklishin approved these changes

2023-02-07 04:17 UTC, merged