Allow setting consumer timeout via queue policy/arg and as consumer argument
rabbitmq/rabbitmq-server pull request #7981
Opened 2023-04-25 10:53 UTC by ikvmw

Close #5437

## Proposed Changes

Add ability to set Consumer Acknowledgement Timeout via a queue/consumer argument as well as a queue policy

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist

_Put an `x` in the boxes that apply.
You can also fill these out after creating the PR.
If you're unsure about any of them, don't hesitate to ask on the mailing list.
We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

## Further Comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.

2023-04-25 10:55 UTC, ikvmw commented
In which version it might go? I need to update release notes and mention on the website

2023-04-25 15:04 UTC, michaelklishin requested changes

2023-04-25 15:04 UTC, michaelklishin commented on deps/rabbit/src/rabbit_channel.erl
> +                                 cfg = #conf{consumer_timeout = GCT}}) ->
This value is unused and it breaks `bazel build`.

2023-04-26 06:31 UTC, michaelklishin commented
We should document the fact that this timeout is (re-)evaluated every so often. When using a low (5-10s) timeout in consumer args some would expect that it will take effect instantly but that takes a moment. Still, this lets folks override the timeout for some queues or consumers and since "override" usually means increase, this initial delay seems perfectly acceptable.

2023-04-26 06:31 UTC, michaelklishin approved these changes

2023-04-26 06:31 UTC, merged