Use pg_local to track AMQP 1.0 connections
rabbitmq/rabbitmq-server pull request #9374
Opened 2023-09-12 12:20 UTC by lukebakken

Fixes #9371

Moves `pg_local` to `rabbit_common`

2023-09-12 13:10 UTC, ansd requested changes
Why is `pg_local` moved to `rabbit_common`?
`rabbit_common` is for code common between `rabbit` and AMQP 0.9.1 client.

2023-09-12 13:21 UTC, lukebakken commented
> Why is `pg_local` moved to `rabbit_common`? `rabbit_common` is for code common between rabbit and AMQP 0.9.1 client.

Did we change the "rules" when it comes to sharing code between sub-projects in `deps/`? As far as I know, plugins _can't_ use code in `deps/rabbit`. cc @dumbbell 

The `rabbitmq_stream` plugin also uses `pg_local` which is "against the rules". At least, the last time I dealt with something like this.

2023-09-12 13:27 UTC, dumbbell commented
> Did we change the "rules" when it comes to sharing code between sub-projects in `deps/`? As far as I know, plugins _can't_ use code in `deps/rabbit`. cc @dumbbell


That's the opposite: plugins must depend on `rabbit`. We should not add code to `rabbit_common` unless the `amqp_client` needs it. Otherwise, the client inherits everything the server depends on.

There are still many circular dependency problems around `rabbit_common`, mostly because of the "direct connection" feature of `amqp_client` which requires a (too) deep knowledge of the server.

As `amqp_client` almost never evolves, we should basically never add code in `rabbit_common`.

2023-09-12 15:15 UTC, lukebakken commented on deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
> +    {authz_backends, print("~tp", Value)};
...and yes, thanks for addressing the other issues in #9022. I figured the most important part of this PR is to fix the issues outlined in #9371

2023-09-12 16:26 UTC, lukebakken commented on deps/rabbitmq_management_agent/src/rabbit_mgmt_format.erl
> +    {authz_backends, print("~tp", Value)};
> However, rabbitmqctl list_amqp10_connections will still show the connection.

@ansd when I run my test AMQP 1.0 application, three AMQP direct connections are created. If I force close all three, my application continues to run, and the original TCP connection remains active. I'm certain your work on #9022 will address this issue!

2023-09-13 06:14 UTC, ansd requested changes
Tests are failing.

2023-09-14 19:14 UTC, michaelklishin commented
Looks like the

``` shell
bazel test //deps/rabbitmq_amqp1_0:proxy_protocol_SUITE
```

failures are consistent.

2023-09-14 20:52 UTC, lukebakken commented
@michaelklishin I'm working on it!

2023-09-15 13:01 UTC, lukebakken commented
@ansd @michaelklishin this should be good to go after the next CI round.

2023-09-16 02:02 UTC, michaelklishin approved these changes
Expanding the list of columns we return for AMQP 1.0 connections would be very nice but this (avoiding crashes and querying supervisors for children) is definitely an improvement as is.

2023-09-16 02:15 UTC, merged