Add a warning banner if any stable feature flag is not enabled
rabbitmq/rabbitmq-server pull request #9893
Opened 2023-11-07 22:01 UTC by dcorbacho

Add an experimental tag on the description to experimental features

References #9148 

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [ ] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)
- [ ] Build system and/or CI

## Checklist
- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass locally with my changes
- [ ] If relevant, I have added necessary documentation to https://github.com/rabbitmq/rabbitmq-website
- [ ] If relevant, I have added this change to the first version(s) in release-notes that I expect to introduce it

2023-12-12 20:15 UTC, michaelklishin commented on deps/rabbitmq_management/src/rabbit_mgmt_wm_deprecated_features.erl
> +%% Copyright (c) 2019-2023 VMware, Inc. or its affiliates.  All rights reserved.
We can no longer use this line, it now must be

```
%% Copyright (c) 2007-2023 Broadcom. All Rights Reserved. The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.  All rights reserved.
```

2023-12-12 20:16 UTC, michaelklishin requested changes
The warning part works as expected for me.

However, navigating to Deprecated Features fails with

```
undefined: There is no template at js/tmpl/deprecated-features.ejs undefined
```

The template is there but it is not picked up for some reason.

2023-12-13 06:37 UTC, dcorbacho commented
Interesting, the template is picked up by `make` but not by `bazel`.

2023-12-13 17:02 UTC, michaelklishin approved these changes

2023-12-13 17:02 UTC, merged